networks:
  networkDashboard:
    driver: bridge

services:
  postgres:
    image: "postgres:16-alpine"
    container_name: nextjs-prisma-dashboard
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=logiacaleuche
    networks:
      - networkDashboard

  adminer:
    image: "adminer:latest"
    container_name: nextjs-adminer-dashboard
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - networkDashboard